[instance]
server-version = "6.5"

[hooks]
schema.update.after = "uv run gel-py --dir queries --no-skip-pydantic-validation"

[[watch]]
files = ["queries/*.edgeql"]
script = "uv run gel-py --dir queries --no-skip-pydantic-validation"

