[project]
name = "scholub"
version = "0.1.0"
description = "Backend of scholub"
readme = "README.md"
requires-python = "==3.13.2"
dependencies = [
  "arxiv==2.2.0",
  "fastapi[standard]==0.115.12",
  "gel==3.0.1",
  "pydantic==2.11.3",
  "python-dotenv==1.1.0",
]
