# AUTOGENERATED FROM 'queries/paper/get_caches.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


@dataclasses.dataclass
class GetCachesResult:
    id: uuid.UUID
    paper_id: str
    modified: datetime.datetime


async def get_caches(
    executor: gel.AsyncIOExecutor,
) -> list[GetCachesResult]:
    return await executor.query(
        """\
        select Paper::Cache {
          paper_id,
          modified
        };\
        """,
    )
