# AUTOGENERATED FROM 'queries/paper/insert_cache.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


@dataclasses.dataclass
class InsertCacheResult:
    id: uuid.UUID
    paper_id: str
    modified: datetime.datetime


async def insert_cache(
    executor: gel.AsyncIOExecutor,
    *,
    paper_id: str,
    modified: datetime.datetime,
) -> InsertCacheResult:
    return await executor.query_single(
        """\
        select (insert Paper::Cache {
          paper_id := <str>$paper_id,
          modified := <datetime>$modified
        } unless conflict on .paper_id else (
          select (update Paper::Cache set {
            modified := <datetime>$modified
          })
        )) {paper_id, modified};\
        """,
        paper_id=paper_id,
        modified=modified,
    )
