# AUTOGENERATED FROM 'queries/posts/get_posts.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import gel
import uuid


@dataclasses.dataclass
class GetPostsResult:
    id: uuid.UUID
    title: str
    description: str
    paper_id: str


async def get_posts(
    executor: gel.AsyncIOExecutor,
) -> list[GetPostsResult]:
    return await executor.query(
        """\
        select Paper::Post {
          title,
          description,
          paper_id
        } order by (.like_count - .dislike_count) desc;\
        """,
    )
