# AUTOGENERATED FROM 'queries/posts/get_posts_like_order.edgeql' WITH:
#     $ gel-py --dir queries


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetPostsLikeOrderResult(NoPydanticValidation):
    id: uuid.UUID
    paper_id: str


async def get_posts_like_order(
    executor: gel.AsyncIOExecutor,
    *,
    start_date: datetime.datetime,
    end_date: datetime.datetime,
) -> list[GetPostsLikeOrderResult]:
    return await executor.query(
        """\
        with post := (select Paper::Post {
          paper_id
        } filter .modified >= <datetime>$start_date and .modified <= <datetime>$end_date)
        select post {paper_id} order by .like_count desc limit 10;\
        """,
        start_date=start_date,
        end_date=end_date,
    )
