# AUTOGENERATED FROM 'queries/user/get_user.edgeql' WITH:
#     $ gel-py --dir queries


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetUserResult(NoPydanticValidation):
    id: uuid.UUID
    email: str
    password: str


async def get_user(
    executor: gel.AsyncIOExecutor,
    *,
    id: uuid.UUID,
) -> GetUserResult | None:
    return await executor.query_single(
        """\
        select User {
          email, password
        } filter .id = <uuid>$id limit 1;\
        """,
        id=id,
    )
