# AUTOGENERATED FROM 'queries/user/get_user_by_name.edgeql' WITH:
#     $ gel-py --dir queries


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetUserByNameResult(NoPydanticValidation):
    id: uuid.UUID
    name: str
    email: str
    password: str


async def get_user_by_name(
    executor: gel.AsyncIOExecutor,
    *,
    name: str,
) -> GetUserByNameResult | None:
    return await executor.query_single(
        """\
        select User {
          name, email, password
        } filter .name = <str>$name limit 1;\
        """,
        name=name,
    )
