# AUTOGENERATED FROM 'queries/user/get_user_by_name.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import gel
import uuid


@dataclasses.dataclass
class GetUserByNameResult:
    id: uuid.UUID
    name: str
    email: str
    password: str


async def get_user_by_name(
    executor: gel.AsyncIOExecutor,
    *,
    name: str,
) -> GetUserByNameResult | None:
    return await executor.query_single(
        """\
        select User {
          name, email, password
        } filter .name = <str>$name limit 1;\
        """,
        name=name,
    )
