# AUTOGENERATED FROM 'queries/user/get_user_by_email.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import gel
import uuid


@dataclasses.dataclass
class GetUserByEmailResult:
    id: uuid.UUID
    name: str
    email: str
    password: str
    bookmarks: list[GetUserByEmailResultBookmarksItem]


@dataclasses.dataclass
class GetUserByEmailResultBookmarksItem:
    id: uuid.UUID


async def get_user_by_email(
    executor: gel.AsyncIOExecutor,
    *,
    email: str,
) -> GetUserByEmailResult | None:
    return await executor.query_single(
        """\
        select User {
          name, email, password, bookmarks
        } filter .email = <str>$email limit 1;\
        """,
        email=email,
    )
