# AUTOGENERATED FROM 'queries/user/insert_user.edgeql' WITH:
#     $ gel-py --dir queries


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class InsertUserResult(NoPydanticValidation):
    id: uuid.UUID


async def insert_user(
    executor: gel.AsyncIOExecutor,
    *,
    name: str,
    email: str,
    password: str,
) -> InsertUserResult:
    return await executor.query_single(
        """\
        insert User {
          name := <str>$name,
          email := <str>$email,
          password := <str>$password
        };\
        """,
        name=name,
        email=email,
        password=password,
    )
