# AUTOGENERATED FROM 'queries/user/insert_user.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import gel
import uuid


@dataclasses.dataclass
class InsertUserResult:
    id: uuid.UUID


async def insert_user(
    executor: gel.AsyncIOExecutor,
    *,
    name: str,
    email: str,
    password: str,
) -> InsertUserResult:
    return await executor.query_single(
        """\
        insert User {
          name := <str>$name,
          email := <str>$email,
          password := <str>$password
        };\
        """,
        name=name,
        email=email,
        password=password,
    )
