# AUTOGENERATED FROM 'queries/get_papers.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


@dataclasses.dataclass
class GetPapersResult:
    id: uuid.UUID
    paper_id: str
    modified: datetime.datetime


async def get_papers(
    executor: gel.AsyncIOExecutor,
) -> list[GetPapersResult]:
    return await executor.query(
        """\
        select Cache {
          paper_id,
          modified
        };\
        """,
    )
