# AUTOGENERATED FROM 'queries/get_paper.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


@dataclasses.dataclass
class GetPaperResult:
    id: uuid.UUID
    paper_id: str
    modified: datetime.datetime


async def get_paper(
    executor: gel.AsyncIOExecutor,
    *,
    paper_id: str,
) -> GetPaperResult | None:
    return await executor.query_single(
        """\
        select Paper {
          paper_id,
          modified
        } filter .paper_id = <str>$paper_id limit 1;\
        """,
        paper_id=paper_id,
    )
