# AUTOGENERATED FROM 'queries/get_user.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import gel
import uuid


@dataclasses.dataclass
class GetUserResult:
    id: uuid.UUID
    email: str
    password: str


async def get_user(
    executor: gel.AsyncIOExecutor,
    *,
    email: str,
) -> GetUserResult | None:
    return await executor.query_single(
        """\
        select User {
          email, password
        } filter .email = <str>$email limit 1;\
        """,
        email=email,
    )
