# AUTOGENERATED FROM 'queries/update_hash.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import gel
import uuid


@dataclasses.dataclass
class UpdateHashResult:
    id: uuid.UUID


async def update_hash(
    executor: gel.AsyncIOExecutor,
    *,
    password: str,
    email: str,
) -> UpdateHashResult | None:
    return await executor.query_single(
        """\
        update User filter .email = <str>$email set {password := <str>$password};\
        """,
        password=password,
        email=email,
    )
