# AUTOGENERATED FROM 'queries/post/get_comment.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


@dataclasses.dataclass
class GetCommentResult:
    id: uuid.UUID
    comments: list[GetCommentResultCommentsItem]


@dataclasses.dataclass
class GetCommentResultCommentsItem:
    id: uuid.UUID
    created: datetime.datetime
    dislike_count: int
    like_count: int
    content: str
    user: GetCommentResultCommentsItemUser


@dataclasses.dataclass
class GetCommentResultCommentsItemUser:
    id: uuid.UUID
    name: str
    email: str


async def get_comment(
    executor: gel.AsyncIOExecutor,
    *,
    post_id: uuid.UUID,
) -> GetCommentResult | None:
    return await executor.query_single(
        """\
        select Paper::Post {
          comments: {
            created,
            dislike_count,
            like_count,
            content,
            user: { id, name, email }
          }
        } filter .id = <uuid>$post_id;\
        """,
        post_id=post_id,
    )
