# AUTOGENERATED FROM 'queries/post/get_comment.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


@dataclasses.dataclass
class GetCommentResult:
    id: uuid.UUID
    user: GetCommentResultUser
    created: datetime.datetime
    like_count: int
    dislike_count: int


@dataclasses.dataclass
class GetCommentResultUser:
    id: uuid.UUID


async def get_comment(
    executor: gel.AsyncIOExecutor,
    *,
    id: uuid.UUID,
) -> GetCommentResult | None:
    return await executor.query_single(
        """\
        select Paper::Comment {
          user,
          created,
          like_count,
          dislike_count
        } filter .id = <uuid>$id;\
        """,
        id=id,
    )
