# AUTOGENERATED FROM 'queries/post/get_post.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


@dataclasses.dataclass
class GetPostResult:
    id: uuid.UUID
    title: str
    body: str
    tag: str
    created: datetime.datetime
    modified: datetime.datetime
    like_count: int
    dislike_count: int


async def get_post(
    executor: gel.AsyncIOExecutor,
    *,
    id: uuid.UUID,
) -> GetPostResult | None:
    return await executor.query_single(
        """\
        select Paper::Post {
          title,
          body,
          tag,
          created,
          modified,
          like_count,
          dislike_count
        } filter .id = <uuid>$id;\
        """,
        id=id,
    )
