# AUTOGENERATED FROM 'queries/post/get_post_list.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


@dataclasses.dataclass
class GetPostListResult:
    id: uuid.UUID
    paper_id: str
    created: datetime.datetime
    title: str
    description: str
    category: str
    tag: str
    modified: datetime.datetime
    like_count: int
    dislike_count: int


async def get_post_list(
    executor: gel.AsyncIOExecutor,
) -> list[GetPostListResult]:
    return await executor.query(
        """\
        SELECT Paper::Post {
          paper_id,
          created,
          title,
          description,
          category,
          tag,
          modified,
          like_count,
          dislike_count
        };\
        """,
    )
