# AUTOGENERATED FROM 'queries/post/get_post_list.edgeql' WITH:
#     $ gel-py --dir queries


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetPostListResult(NoPydanticValidation):
    id: uuid.UUID
    paper_id: str
    created: datetime.datetime
    title: str
    description: str
    category: str
    tag: str
    modified: datetime.datetime
    like_count: int
    dislike_count: int


async def get_post_list(
    executor: gel.AsyncIOExecutor,
) -> list[GetPostListResult]:
    return await executor.query(
        """\
        SELECT Paper::Post {
          paper_id,
          created,
          title,
          description,
          category,
          tag,
          modified,
          like_count,
          dislike_count
        };\
        """,
    )
