# AUTOGENERATED FROM 'queries/post/get_post.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


@dataclasses.dataclass
class GetPostResult:
    # id: uuid.UUID
    title: str
    description: str
    paper_id: str
    category: str
    tag: str
    created: datetime.datetime
    modified: datetime.datetime
    like_count: int
    dislike_count: int


async def get_post(
    executor: gel.AsyncIOExecutor,
    *,
    paper_id: str,
) -> GetPostResult | None:
    
    result = await executor.query_single(
        """\
        select Paper::Post {
          title,
          description,
          paper_id,
          category,
          tag,
          created,
          modified,
          like_count,
          dislike_count
        } filter .paper_id = <str>$paper_id;\
        """,
        paper_id=paper_id,
    )

    
    return GetPostResult(
        title=result.title,
        description=result.description,
        paper_id=result.paper_id,
        category=result.category,
        tag=result.tag,
        created=result.created,
        modified=result.modified,
        like_count=result.like_count,
        dislike_count=result.dislike_count
    ) if result else None