# AUTOGENERATED FROM 'queries/post/insert_post.edgeql' WITH:
#     $ gel-py --dir queries


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class InsertPostResult(NoPydanticValidation):
    id: uuid.UUID


async def insert_post(
    executor: gel.AsyncIOExecutor,
    *,
    title: str,
    description: str,
    paper_id: str,
    category: str,
    tag: str,
) -> InsertPostResult:
    return await executor.query_single(
        """\
        insert Paper::Post {
          title := <str>$title,
          description := <str>$description,
          paper_id := <str>$paper_id,
          category := <str>$category,
          tag := <str>$tag
        };\
        """,
        title=title,
        description=description,
        paper_id=paper_id,
        category=category,
        tag=tag,
    )
