# AUTOGENERATED FROM 'queries/post/insert_post.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import gel
import uuid


@dataclasses.dataclass
class InsertPostResult:
    id: uuid.UUID


async def insert_post(
    executor: gel.AsyncIOExecutor,
    *,
    title: str,
    description: str,
    paper_id: str,
    category: str,
    tag: str,
) -> InsertPostResult:
    return await executor.query_single(
        """\
        insert Paper::Post {
          title := <str>$title,
          description := <str>$description,
          paper_id := <str>$paper_id,
          category := <str>$category,
          tag := <str>$tag
        };\
        """,
        title=title,
        description=description,
        paper_id=paper_id,
        category=category,
        tag=tag,
    )
