# AUTOGENERATED FROM 'queries/post/insert_post.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import gel
import uuid


@dataclasses.dataclass
class InsertPostResult:
    id: uuid.UUID


async def insert_post(
    executor: gel.AsyncIOExecutor,
    *,
    title: str,
    body: str,
    tag: str,
) -> InsertPostResult:
    return await executor.query_single(
        """\
        insert Paper::Post {
          title := <str>$title,
          body := <str>$body,
          tag := <str>$tag
        };\
        """,
        title=title,
        body=body,
        tag=tag,
    )
