# AUTOGENERATED FROM 'queries/post/post_comment.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import gel
import uuid


@dataclasses.dataclass
class PostCommentResult:
    id: uuid.UUID


async def post_comment(
    executor: gel.AsyncIOExecutor,
    *,
    content: str,
    user_id: uuid.UUID,
    post_id: uuid.UUID,
) -> PostCommentResult | None:
    return await executor.query_single(
        """\
        update Paper::Post
        filter .id = <uuid>$post_id
        set {
          comments += (
            insert Paper::Comment {
              created := datetime_current(),
              content := <str>$content,
              user := (select User filter .id = <uuid>$user_id)
            }
          )
        };\
        """,
        content=content,
        user_id=user_id,
        post_id=post_id,
    )
