# AUTOGENERATED FROM 'queries/tests/get_reaction.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import gel
import uuid


@dataclasses.dataclass
class GetReactionResult:
    id: uuid.UUID
    like_count: int
    dislike_count: int


async def get_reaction(
    executor: gel.AsyncIOExecutor,
    *,
    paper_id: str,
) -> GetReactionResult | None:
    return await executor.query_single(
        """\
        select Paper::Post {
          like_count,
          dislike_count
        } filter .paper_id = <str>$paper_id;\
        """,
        paper_id=paper_id,
    )
