# AUTOGENERATED FROM 'queries/tests/get_comment_reaction.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import gel
import uuid


@dataclasses.dataclass
class GetCommentReactionResult:
    id: uuid.UUID
    like_count: int
    dislike_count: int


async def get_comment_reaction(
    executor: gel.AsyncIOExecutor,
    *,
    id: uuid.UUID,
) -> GetCommentReactionResult | None:
    return await executor.query_single(
        """\
        select Comment::Comment {
          like_count,
          dislike_count
        } filter .id = <uuid>$id;\
        """,
        id=id,
    )
