# AUTOGENERATED FROM 'queries/tests/get_reaction.edgeql' WITH:
#     $ gel-py --dir queries


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetReactionResult(NoPydanticValidation):
    id: uuid.UUID
    like_count: int
    dislike_count: int


async def get_reaction(
    executor: gel.AsyncIOExecutor,
    *,
    paper_id: str,
) -> GetReactionResult | None:
    return await executor.query_single(
        """\
        select Paper::Post {
          like_count,
          dislike_count
        } filter .paper_id = <str>$paper_id;\
        """,
        paper_id=paper_id,
    )
