# AUTOGENERATED FROM 'queries/cache/gc_cache.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


@dataclasses.dataclass
class GcCacheResult:
    id: uuid.UUID


async def gc_cache(
    executor: gel.AsyncIOExecutor,
    *,
    datetime: datetime.datetime,
) -> list[GcCacheResult]:
    return await executor.query(
        """\
        delete Paper::Cache filter .created < <datetime>$datetime\
        """,
        datetime=datetime,
    )
