# AUTOGENERATED FROM 'queries/cache/insert_cache.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import gel
import uuid


@dataclasses.dataclass
class InsertCacheResult:
    id: uuid.UUID


async def insert_cache(
    executor: gel.AsyncIOExecutor,
    *,
    paper_id: str,
) -> InsertCacheResult:
    return await executor.query_single(
        """\
        insert Paper::Cache {
          paper_id := <str>$paper_id
        }\
        """,
        paper_id=paper_id,
    )
