on:
  push:
  pull_request:
  merge_group:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5

      - name: setup
        run: |
          echo "SECRET_KEY=test" > .env
          uv tool install gel
          $HOME/.local/bin/gel project init --non-interactive
          uv sync

      - name: test
        run: "uv run pytest ./tests"
