on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: astral-sh/setup-uv@v5

      - name: setup
        run: |
          uv tool install gel
          $HOME/.local/bin/gel project init --non-interactive
          uv sync

      - name: test
        run: "uv run pytest ./tests"
