# AUTOGENERATED FROM 'queries/comment/delete_comment.edgeql' WITH:
#     $ gel-py --dir queries --no-skip-pydantic-validation


from __future__ import annotations
import dataclasses
import gel
import uuid


@dataclasses.dataclass
class DeleteCommentResult:
    id: uuid.UUID


async def delete_comment(
    executor: gel.AsyncIOExecutor,
    *,
    id: uuid.UUID,
) -> DeleteCommentResult | None:
    return await executor.query_single(
        """\
        delete Comment::Comment filter .id = <uuid>$id;\
        """,
        id=id,
    )
