# AUTOGENERATED FROM 'queries/comment/select_reaction.edgeql' WITH:
#     $ gel-py --dir queries


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class SelectReactionResult(NoPydanticValidation):
    id: uuid.UUID
    is_like: bool


async def select_reaction(
    executor: gel.AsyncIOExecutor,
    *,
    comment_id: uuid.UUID,
    user_id: uuid.UUID,
) -> SelectReactionResult | None:
    return await executor.query_single(
        """\
        with
          comment := (select Comment::Comment filter .id = <uuid>$comment_id limit 1),
          user := (select User filter .id = <uuid>$user_id limit 1),
        select Comment::Reaction {
          is_like
        } filter .comment = comment and .user = user limit 1;\
        """,
        comment_id=comment_id,
        user_id=user_id,
    )
